/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-08-20 02:18:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.cmmn;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.util.CmmUtil;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/view/cmmn/user/userLoginBody.jsp", Long.valueOf(1534729901222L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("poly.util.CmmUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><!-- 반응형 웹 설정 -->\r\n");
      out.write("<title>트럭 왔냠 - 메인 페이지</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin: 0 auto\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div style=\"text-align:center; width:100%;\">\r\n");
      out.write("\t\t<h1>트럭왔냠 메인 페이지</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div style=\"text-align:center; width:100%;\">\r\n");
      out.write("\t\t<h4><a href=\"/consumer/main.do\">비회원으로 들어가기</a></h4>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t \t<div>");
      out.write("\r\n");
      out.write("\r\n");

	String joinCode = CmmUtil.nvl ((String)session.getAttribute("joinCode"));

      out.write('\r');
      out.write('\n');
      out.print(joinCode );
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!--  로그인 css -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\t    padding-top: 150px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-login {\r\n");
      out.write("\t\tborder-color: #ccc;\r\n");
      out.write("\t\t-webkit-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);\r\n");
      out.write("\t\t-moz-box-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);\r\n");
      out.write("\t\tbox-shadow: 0px 2px 3px 0px rgba(0,0,0,0.2);\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-login>.panel-heading {\r\n");
      out.write("\t\tcolor: #00415d;\r\n");
      out.write("\t\tbackground-color: #fff;\r\n");
      out.write("\t\tborder-color: #fff;\r\n");
      out.write("\t\ttext-align:center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-login>.panel-heading a{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor: #666;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t\t-webkit-transition: all 0.1s linear;\r\n");
      out.write("\t\t-moz-transition: all 0.1s linear;\r\n");
      out.write("\t\ttransition: all 0.1s linear;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-login>.panel-heading a.active{\r\n");
      out.write("\t\tcolor: #029f5b;\r\n");
      out.write("\t\tfont-size: 18px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-login>.panel-heading hr{\r\n");
      out.write("\t\tmargin-top: 10px;\r\n");
      out.write("\t\tmargin-bottom: 0px;\r\n");
      out.write("\t\tclear: both;\r\n");
      out.write("\t\tborder: 0;\r\n");
      out.write("\t\theight: 1px;\r\n");
      out.write("\t\tbackground-image: -webkit-linear-gradient(left,rgba(0, 0, 0, 0),rgba(0, 0, 0, 0.15),rgba(0, 0, 0, 0));\r\n");
      out.write("\t\tbackground-image: -moz-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));\r\n");
      out.write("\t\tbackground-image: -ms-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));\r\n");
      out.write("\t\tbackground-image: -o-linear-gradient(left,rgba(0,0,0,0),rgba(0,0,0,0.15),rgba(0,0,0,0));\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-login input[type=\"text\"],.panel-login input[type=\"email\"],.panel-login input[type=\"password\"] {\r\n");
      out.write("\t\theight: 45px;\r\n");
      out.write("\t\tborder: 1px solid #ddd;\r\n");
      out.write("\t\tfont-size: 16px;\r\n");
      out.write("\t\t-webkit-transition: all 0.1s linear;\r\n");
      out.write("\t\t-moz-transition: all 0.1s linear;\r\n");
      out.write("\t\ttransition: all 0.1s linear;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-login input:hover,\r\n");
      out.write("\t.panel-login input:focus {\r\n");
      out.write("\t\toutline:none;\r\n");
      out.write("\t\t-webkit-box-shadow: none;\r\n");
      out.write("\t\t-moz-box-shadow: none;\r\n");
      out.write("\t\tbox-shadow: none;\r\n");
      out.write("\t\tborder-color: #ccc;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-login {\r\n");
      out.write("\t\tbackground-color: #59B2E0;\r\n");
      out.write("\t\toutline: none;\r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\tfont-weight: normal;\r\n");
      out.write("\t\tpadding: 14px 0;\r\n");
      out.write("\t\ttext-transform: uppercase;\r\n");
      out.write("\t\tborder-color: #59B2E6;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-login:hover,\r\n");
      out.write("\t.btn-login:focus {\r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t\tbackground-color: #53A3CD;\r\n");
      out.write("\t\tborder-color: #53A3CD;\r\n");
      out.write("\t}\r\n");
      out.write("\t.forgot-id_password {\r\n");
      out.write("\t\ttext-decoration: underline;\r\n");
      out.write("\t\tcolor: #888;\r\n");
      out.write("\t}\r\n");
      out.write("\t.forgot-id_password:hover,\r\n");
      out.write("\t.forgot-id_password:focus {\r\n");
      out.write("\t\ttext-decoration: underline;\r\n");
      out.write("\t\tcolor: #666;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.btn-register {\r\n");
      out.write("\t\tbackground-color: #1CB94E;\r\n");
      out.write("\t\toutline: none;\r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\tfont-weight: normal;\r\n");
      out.write("\t\tpadding: 14px 0;\r\n");
      out.write("\t\ttext-transform: uppercase;\r\n");
      out.write("\t\tborder-color: #1CB94A;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn-register:hover,\r\n");
      out.write("\t.btn-register:focus {\r\n");
      out.write("\t\tcolor: #fff;\r\n");
      out.write("\t\tbackground-color: #1CA347;\r\n");
      out.write("\t\tborder-color: #1CA347;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.gender_color{\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("</style>\r\n");
      out.write("<!--  로그인 끝 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 시작 -->\r\n");
      out.write("\t<link href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css\" rel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!------ Include the above in your HEAD tag ---------->\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t    \t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 로그인 회원가입 TOP부분 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\" id=\"login-form-link\" class=\"active\">로그인</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\"  id=\"register-form-link\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 로그인 회원가입 TOP부분 -->\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 로그인 회원가입 정보입력 부분 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 로그인 정보입력 시작 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"login-form\" action=\"/cmmn/user/loginProc.do\" method=\"post\" role=\"form\" style=\"display: block;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"user_Email\" id=\"email\" tabindex=\"1\" class=\"form-control\" placeholder=\"이메일\" value=\"\" data-msg=\"이메일을\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"user_Pwd\" id=\"userPassword\" tabindex=\"2\" class=\"form-control\" placeholder=\"비밀번호\" data-msg=\"비밀번호를\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\" tabindex=\"3\" class=\"\" name=\"remember\" id=\"remember\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"remember\"> 아이디 기억하기</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"login-submit\" id=\"login-submit\" tabindex=\"4\" class=\"form-control btn btn-login\" value=\"로그인\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"/cmmn/user/userFindInfo.do\" tabindex=\"5\" class=\"forgot-id_password\">아이디/비밀번호 찾기</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 로그인 정보입력 끝 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 회원가입 정보입력 시작 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form id=\"register-form\" action=\"/cmmn/user/userRegProc.do\" method=\"post\" role=\"form\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"email\" class=\"form-control\" id=\"email_input\" placeholder=\"*이메일 입력\" data-msg=\"이메일을\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"button\" class=\"btn btn-primary\" id=\"emailCheck\" value=\"이메일 중복체크\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"userPassword\" id=\"register_userPassword\" tabindex=\"2\" class=\"form-control\" placeholder=\"비밀번호\" value=\"\" data-msg=\"비밀번호를\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font id=\"length\" size=\"2\" color=\"red\"></font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" name=\"confirm-password\" id=\"register_confirm-password\" tabindex=\"2\" class=\"form-control\" placeholder=\"비밀번호확인\" data-msg=\"비밀번호확인을\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font id=\"check\" size=\"2\" color=\"red\"></font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"nickname\" id=\"nickname\" tabindex=\"3\" class=\"form-control\" placeholder=\"닉네임\" data-msg=\"닉네임을\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select class=\"form-control\" tabindex=\"4\" class=\"gender_color\" name=\"gender\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option class=\"gender_color\" data-msg=\"*성별을 \">*성별</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option class=\"gender_color\" value=\"M\">남자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option class=\"gender_color\" value=\"F\">여자</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"phone\" id=\"phone\" tabindex=\"5\" class=\"form-control\" placeholder=\"핸드폰 번호 입력\" data-msg=\"핸드폰 번호를\" maxlength=\"15\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<p><a class=\"btn btn-primary col-sm-12\" data-target=\"#modal1\" data-toggle=\"modal\" id=\"agree\" >회원약관</a></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 가입하기 버튼 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"register-submit\" id=\"register-submit\" tabindex=\"6\" class=\"form-control btn btn-register\" value=\"가입하기\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 이메일 유효성 검사를 위한 value   -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"0\" id=\"count\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 이메일 인증 회원 상태   -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"AuthN\" name=\"userStatus\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!-- 가입하기 버튼끝  -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- 회원가입 정보입력 끝 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 로그인 회원가입 정보입력 부분 -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 회원 약관 모달 -->\r\n");
      out.write("<div class=\"modal\" id=\"modal1\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("\r\n");
      out.write("      <!-- 회원약관 모달 Header -->\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h4 class=\"modal-title\">트럭왔냠 회원약관</h4>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 회원약관 body -->\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("         <div class=\"col-lg-10\" id=\"provision\">\r\n");
      out.write("                    <textarea class=\"form-control\" rows=\"8\" style=\"resize:none\" readonly>약관동의\r\n");
      out.write("                    </textarea>\r\n");
      out.write("                    <div class=\"radio\">\r\n");
      out.write("                        <label>\r\n");
      out.write("                            <input type=\"radio\" id=\"radioY\" name=\"provisionYn\" value=\"Y\" autofocus=\"autofocus\" />\r\n");
      out.write("                           \t\t 동의합니다.\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"radio\">\r\n");
      out.write("                        <label>\r\n");
      out.write("                            <input type=\"radio\" id=\"radioN\" name=\"provisionYn\" value=\"N\">\r\n");
      out.write("                            \t동의하지 않습니다.\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- 회원약관 footer -->\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\" id=\"provistionY_Y\" >확인</button>\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 로그인/회원가입js -->\r\n");
      out.write("\t<script>\r\n");
      out.write("\t<!--로그인 처음 화면 js-->\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t    $('#login-form-link').click(function(e) {\r\n");
      out.write("\t\t\t$(\"#login-form\").delay(100).fadeIn(100);\r\n");
      out.write("\t \t\t$(\"#register-form\").fadeOut(100);\r\n");
      out.write("\t\t\t$('#register-form-link').removeClass('active');\r\n");
      out.write("\t\t\t$(this).addClass('active');\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#register-form-link').click(function(e) {\r\n");
      out.write("\t\t\t$(\"#register-form\").delay(100).fadeIn(100);\r\n");
      out.write("\t \t\t$(\"#login-form\").fadeOut(100);\r\n");
      out.write("\t\t\t$('#login-form-link').removeClass('active');\r\n");
      out.write("\t\t\t$(this).addClass('active');\r\n");
      out.write("\t\t\te.preventDefault('btn-warning');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\t<!--로그인 처음 화면 js끝-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 로그인 빈칸 정보 확인 js 시작-->\r\n");
      out.write("\t\t$('#login-submit').on('click',function(){\r\n");
      out.write("\t\t\tif($('#email').val() ==''){\r\n");
      out.write("\t\t\t\t$('#email').focus();\r\n");
      out.write("\t\t\t\talert($('#email').attr('data-msg')+ '입력해주세요');\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}; \r\n");
      out.write("\t\t\tif($('#userPassword').val() ==''){\r\n");
      out.write("\t\t\t\t$('#userPassword').focus();\r\n");
      out.write("\t\t\t\talert($('#userPassword').attr('data-msg')+ '입력해주세요');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 로그인 빈칸 정보 확인 js 시작-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--******************************************************아래부터는 회원가입******************-->\r\n");
      out.write("\t\t<!--비밀번호확인 체크 시작js-->\r\n");
      out.write("\t\t//비밀번호 조합\r\n");
      out.write("\t\t   function checkUnion(str){\r\n");
      out.write("\t\t      var reg1=/^[a-zA-Z0-9]{8,20}$/;//대문자 소만자 8 -20 자리 허용\r\n");
      out.write("\t\t      var reg2=/[a-zA-Z]/g;\r\n");
      out.write("\t\t      var reg3=/[0-9]/g;\r\n");
      out.write("\t\t      return(reg1.test(str) && reg2.test(str) &&reg3.test(str))\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//비밀번호 일치 여부 확인 \r\n");
      out.write("\t\t\t$(function(){\r\n");
      out.write("\t\t\t\tvar register_userPassword = $('#register_userPassword');\r\n");
      out.write("\t\t\t\t$('#register_userPassword').keyup(function(){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$('font[id=check]').text('');\r\n");
      out.write("\t\t\t\t\tif(!checkUnion(register_userPassword.val())){\r\n");
      out.write("\t\t\t\t\t   \r\n");
      out.write("\t\t\t\t\t\t$('font[id=length]').text('');\r\n");
      out.write("\t\t\t\t\t\t$('font[id=length]').html(\"8자리 이상 20자리 이하의 [영문+숫자] 조합\");\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$('font[id=length]').css('color','green');\r\n");
      out.write("\t\t\t\t\t\t$('font[id=length]').html(\"적합\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('#register_confirm-password').keyup(function(){\r\n");
      out.write("\t\t\t\t\tif($('#register_userPassword').val() != $('#register_confirm-password').val()){\r\n");
      out.write("\t\t\t\t\t\t$('font[id=check]').text('');\r\n");
      out.write("\t\t\t\t\t\t$('font[id=check]').css('color','red');\r\n");
      out.write("\t\t\t\t\t\t$('font[id=check]').html(\"암호 틀림\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$('font[id=check]').text('');\r\n");
      out.write("\t\t\t\t\t\t$('font[id=check]').css('color','green');\r\n");
      out.write("\t\t\t\t\t\t$('font[id=check]').html(\"암호 일치\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});//confirm keyup\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--비밀번호확인 체크끝js-->\r\n");
      out.write("\t\t//전화번호 유효성 검사 함수\r\n");
      out.write("\t\t   $('#phone').keydown(function(e){\r\n");
      out.write("\t\t      if((e.keyCode<48 || e.keyCode>57)&&e.keyCode!=8&&(e.keyCode<96||e.keyCode>105)){\r\n");
      out.write("\t\t         alert(\"전화번호는 숫자만 입력됩니다.\");\r\n");
      out.write("\t\t         return false;\r\n");
      out.write("\t\t      }\r\n");
      out.write("\t\t   });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--이메일 체크js -->\r\n");
      out.write("\t\t$('#emailCheck').on('click',function(){\r\n");
      out.write(" \t\t\t$.ajax({\r\n");
      out.write(" \t\t\t\ttype:'POST',\r\n");
      out.write(" \t\t\t\turl:'/cmmn/user/emailCheck.do',\r\n");
      out.write(" \t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\t\"email\" : $('#email_input').val()\t \t\t\t\t\t\r\n");
      out.write(" \t\t\t\t},\r\n");
      out.write(" \t\t\t\tsuccess : function(data){\r\n");
      out.write("\t \t\t\t\tif(data > 0 ){\r\n");
      out.write("\t \t\t\t\t\t$('#emailCheck').val('사용중인 이메일');\r\n");
      out.write("\t \t\t\t\t\t$('#count').val('0');\r\n");
      out.write("\t \t\t\t\t\t$('#emailCheck').removeClass('btn-warning')\r\n");
      out.write("\t \t\t\t\t\t$('#emailCheck').removeClass('btn-primary')\r\n");
      out.write("\t \t\t\t\t\t$('#emailCheck').addClass('btn-danger');\r\n");
      out.write("\t \t\t\t\t}else{\r\n");
      out.write("\t \t\t\t\t\t$('#emailCheck').val('사용가능 이메일');\r\n");
      out.write("\t \t\t\t\t\t$('#emailCheck').removeClass('btn-warning')\r\n");
      out.write("\t \t\t\t\t\t$('#emailCheck').removeClass('btn-danger')\r\n");
      out.write("\t \t\t\t\t\t$('#emailCheck').addClass('btn-primary active');\r\n");
      out.write("\t \t\t\t\t\t$('#count').val('1');\r\n");
      out.write("\t \t\t\t\t}\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\t},//success\r\n");
      out.write("\t \t\t\terror:function(x,e){\r\n");
      out.write("\t\t\t\t\tif(x.status==0){\r\n");
      out.write("\t\t\t            alert('네트워크가 정상적으로 동작하지 않습니다.');\r\n");
      out.write("\t\t\t            alert('네트워크 상태를 확인 하거나 업체에게 문의해 주세요.')\r\n");
      out.write("\t\t\t            }else if(x.status==404){\r\n");
      out.write("\t\t\t            alert('페이지를 찾을수가 없습니다. 지금은 주문을 받을 수 없습니다. 업체에게 문의하세요.');\r\n");
      out.write("\t\t\t            }else if(x.status==500){\r\n");
      out.write("\t\t\t            alert('서버에서 오류가 발생했습니다. 지금은 주문을 받을 수 없습니다. 업체에게 문의하세요.');\r\n");
      out.write("\t\t\t            }else if(e=='parsererror'){\r\n");
      out.write("\t\t\t            alert('json파싱에 실패했습니다.');\r\n");
      out.write("\t\t\t            }else if(e=='timeout'){\r\n");
      out.write("\t\t\t            alert('응답 요청 시간이 지났습니다.');\r\n");
      out.write("\t\t\t            }else {\r\n");
      out.write("\t\t\t            alert('Unknow Error.n'+x.responseText);\r\n");
      out.write("\t\t\t            }\r\n");
      out.write("\t\t\t    }\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t\t})//ajax\r\n");
      out.write(" \t\t\t\r\n");
      out.write(" \t\t});//on click\r\n");
      out.write(" \t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--회원약관js provistionY_Y-->\r\n");
      out.write("\t\t//회원가입약관\r\n");
      out.write("\t\t$('#provistionY_Y').click(function(e){\r\n");
      out.write("\t\t\t// alert($('#radioY').is(\":checked\"));\r\n");
      out.write("\t\t\t if($('#radioY').is(\":checked\")){\r\n");
      out.write("\t\t\t \t\r\n");
      out.write("\t\t\t\t$('#agree').removeClass('btn-warning')\r\n");
      out.write("\t\t\t\t$('#agree').attr('background-color','48ABFF');\r\n");
      out.write("\t\t\t\t$('#modal1').fadeOut(100);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\talert('동의하셔야 다음으로 진행할 수 있습니다.');\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t<!--회원약관js끝-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--가입하기 빈칸 있는지 정보확인 js시작-->\r\n");
      out.write("\t\t$('#register-submit').on('click',function(){\r\n");
      out.write("\t\t\t \tif($('#email_input').val() ==''){\r\n");
      out.write("\t\t\t\t\t$('#email_input').focus();\r\n");
      out.write("\t\t\t\t\talert($('#email_input').attr('data-msg')+ '입력해주세요');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//이메일 유효성 검사\r\n");
      out.write("\t\t\t\tvar emavld = /[a-z0-9]{2,}@[a-z0-9-]{2,}\\.[a-z0-9]{2,}/i;\r\n");
      out.write("\t\t\t\tif(!emavld.test($('#email_input').val())){\r\n");
      out.write("\t\t\t         alert(\"이메일 형식을 올바르게 입력해주세요 \")\r\n");
      out.write("\t\t\t         email.focus();\r\n");
      out.write("\t\t\t         return false;\r\n");
      out.write("\t\t\t      }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif($('#count').val() == '0'){\r\n");
      out.write("\t\t\t\t\talert(\"이메일 인증을 해주세요\");\r\n");
      out.write("\t\t\t\t\t$('#email_input').focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\tif($('#register_userPassword').val() ==''){\r\n");
      out.write("\t\t\t\t\t$('#register_userPassword').focus();\r\n");
      out.write("\t\t\t\t\talert($('#register_userPassword').attr('data-msg')+ '입력해주세요');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tif($('#register_confirm-password').val() ==''){\r\n");
      out.write("\t\t\t\t\t$('#register_confirm-password').focus();\r\n");
      out.write("\t\t\t\t\talert($('#register_confirm-password').attr('data-msg')+ '입력해주세요');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t if($('#register_userPassword').val() != $('#register_confirm-password').val()){\r\n");
      out.write("\t\t\t\t\t$('#register_confirm-password').focus();\r\n");
      out.write("\t\t\t\t\talert('비밀번호/확인 동일하게 설정해주세요');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t//비밀번호 유효성 검사\r\n");
      out.write("\t\t\t\tif(!checkUnion($('#register_userPassword').val())){\r\n");
      out.write("\t\t\t         alert(\"비밀번호 유효성검사에 어긋남\");\r\n");
      out.write("\t\t\t         $('#register_userPassword').focus();\r\n");
      out.write("\t\t\t         return false;\r\n");
      out.write("\t\t\t      };\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif($('#nickname').val() ==''){\r\n");
      out.write("\t\t\t\t\t$('#nickname').focus();\r\n");
      out.write("\t\t\t\t\talert($('#nickname').attr('data-msg')+ '입력해주세요');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tif($('select > option:selected').val() == \"*성별\"){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\talert($('select > option:selected').attr('data-msg')+ '선택해주세요');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif($('#phone').val() ==''){\r\n");
      out.write("\t\t\t\t\t$('#phone').focus();\r\n");
      out.write("\t\t\t\t\talert($('#phone').attr('data-msg')+ '입력해주세요');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tif($('#radioY').is(\":checked\")){\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert('약관 동의 해주세요');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--가입하기 빈칸 있는지 정보확인js끝-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<!--  로그인/회원가입js끝 -->");
      out.write("</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("<style>\r\n");
      out.write("\t/* 로그인/회원가입 글자 색상 */\r\n");
      out.write("\t.panel-login>.panel-heading a{\r\n");
      out.write("\t\tcolor:3071A9;\r\n");
      out.write("\t}\r\n");
      out.write("\t.panel-login>.panel-heading a.active{\r\n");
      out.write("\t\tcolor:48ABFF;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 폼 자동 채우기 색상 교체*/\r\n");
      out.write("\tinput:-webkit-autofill {\r\n");
      out.write("\t    -webkit-box-shadow:0 0 0 50px white inset; /* Change the color to your own background color */\r\n");
      out.write("\t    -webkit-text-fill-color: #333;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput:-webkit-autofill:focus {\r\n");
      out.write("\t    -webkit-box-shadow: /*your box-shadow*/,0 0 0 50px white inset;\r\n");
      out.write("\t    -webkit-text-fill-color: #333;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* 로그인 버튼 */\r\n");
      out.write("\t#login-submit{\r\n");
      out.write("\t\tcolor: #428bca;\r\n");
      out.write("  \t \tfont-size: 20px;\r\n");
      out.write("   \t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* 이메일 중복 체크  버튼*/\r\n");
      out.write("\t#emailCheck{\r\n");
      out.write("\t\theight:45px;\r\n");
      out.write("\t}\r\n");
      out.write("\t/* 회원약관 버튼 */\r\n");
      out.write("\t#agree{\r\n");
      out.write("\t\theight:45px;\r\n");
      out.write("\t\tpadding: 10px 0;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
