/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-08-20 04:32:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.consumer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.dto.consumer.CONSUMER_ImageDTO;
import java.util.List;
import poly.util.CmmUtil;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/view/consumer/maintestCssScript.jsp", Long.valueOf(1534729902207L));
    _jspx_dependants.put("/WEB-INF/view/consumer/topCssScript.jsp", Long.valueOf(1534729902038L));
    _jspx_dependants.put("/WEB-INF/view/consumer/topBody.jsp", Long.valueOf(1534729901175L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.dto.consumer.CONSUMER_ImageDTO");
    _jspx_imports_classes.add("poly.util.CmmUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 List<CONSUMER_ImageDTO> imgDTOs = (List<CONSUMER_ImageDTO>)request.getAttribute("imgDTOs");  
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>트럭왔냠 - 메인페이지</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 창원이형꺼 top -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<!-- <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\"> -->\r\n");
      out.write("\t<!-- <link rel=\"stylesheet\" href=\"/img/b.css\" /> -->    \r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- 창원이형이 주신 css 시작  -->\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\r\n");
      out.write(" \tbody {\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t    font-family: \"Lato\", sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ta {\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tcolor : black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 사이드 메뉴 시작 */\r\n");
      out.write("\t.navigation {\r\n");
      out.write("\t\tposition:relative;\r\n");
      out.write("\t\theight:130px;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t.menuButton {\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t.sidenav {\r\n");
      out.write("\t    height: 100%;\r\n");
      out.write("\t    width: 0;\r\n");
      out.write("\t    position: fixed;\r\n");
      out.write("\t    z-index: 2;\r\n");
      out.write("\t    top: 0;\r\n");
      out.write("\t    left: 0;\r\n");
      out.write("\t    overflow-x: hidden;\r\n");
      out.write("\t    transition: 0.4s;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t.sidenav a {\r\n");
      out.write("\t    padding: 8px 8px 8px 32px;\r\n");
      out.write("\t    text-decoration: none;\r\n");
      out.write("\t    font-size: 20px;\r\n");
      out.write("\t    color: #818181;\r\n");
      out.write("\t    display:block;\r\n");
      out.write("\t    transition: 0.3s;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.sidenav a:hover {\r\n");
      out.write("\t    color: #f1f1f1;\r\n");
      out.write("\t}\r\n");
      out.write("\t#mySidenav{\r\n");
      out.write("\t\tz-index:101;\r\n");
      out.write("\t}\r\n");
      out.write("\t#sidenav_outer {\r\n");
      out.write("\t\t\r\n");
      out.write("\t    background-color: rgba(0,0,0,0.45);\r\n");
      out.write("\t\twidth:0;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\t\tposition:fixed;\r\n");
      out.write("\t\tleft:0px; top:0px;\r\n");
      out.write("\t\tz-index:100;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t#sidenav_inner {\r\n");
      out.write("\t\tbackground-color: rgba(0,0,0);\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\theight:100%;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t.closebtn {\r\n");
      out.write("\t\tfont-size:50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t/**************/\r\n");
      out.write("\t\r\n");
      out.write("\t/* 1번째 행 최상단 날씨 / 지역 div */\r\n");
      out.write("\t.topFirstContainer{\r\n");
      out.write("\t\toverflow:hidden; height:24px;\r\n");
      out.write("\t\tbackground-color: #444444;\r\n");
      out.write("\t}\r\n");
      out.write("\t.topFirstContainer a{\r\n");
      out.write("\t\tdisplay:table-cell; color:#cbcbcb; font-size:12px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#nav_top_left{\r\n");
      out.write("\t\tfloat:left; display:table; font-weight:bold;\r\n");
      out.write("\t}\r\n");
      out.write("\t#nav_top_left img{\r\n");
      out.write("\t\tmargin-left:10px;\r\n");
      out.write("\t\theight:24px;\r\n");
      out.write("\t\tmargin-right:3px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#nav_top_right{\r\n");
      out.write("\t\tfloat:right; display:table; height:100%; padding-top:1px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" \t/* 2번째 행 메뉴 / 검색 / 뒤로가기 버튼 div  */\r\n");
      out.write(" \t.topSecondContainer {\r\n");
      out.write(" \t\theight:56px; \r\n");
      out.write(" \t\tbackground: #333333;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t.menuButton{\r\n");
      out.write(" \t\tfloat:left;\r\n");
      out.write(" \t}\r\n");
      out.write("\r\n");
      out.write(" \t/* 메인 로고 그림 */\r\n");
      out.write(" \t#logo_main{\r\n");
      out.write(" \t\tdisplay:table; margin: 0 auto;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \t/* 검색 부분 */\r\n");
      out.write(" \t#searchBttnContainer {\r\n");
      out.write(" \t\tfloat:right; visibility: visible;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#searchBarContainer{\r\n");
      out.write(" \t\tposition: relative; \r\n");
      out.write(" \t\theight:48px; width:100%;\r\n");
      out.write(" \t\tright:0; display:none;\r\n");
      out.write(" \t\tpadding-left:5px; padding-right:5px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#searchBarContainer > input[type=text] {\r\n");
      out.write(" \t\tmargin-top:4px;\r\n");
      out.write(" \t\twidth:77%; height:75%;\r\n");
      out.write(" \t\tborder:1px solid #cccccc;\r\n");
      out.write(" \t\tbox-sizing:border-box;\r\n");
      out.write(" \t\tpadding-left:10px;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t#searchButtonClose{\r\n");
      out.write(" \t\tfloat:right;\r\n");
      out.write(" \t}\r\n");
      out.write("\t#submitBttn {\r\n");
      out.write("\t\tbackground-color:#444444;\r\n");
      out.write("\t\tborder:1px solid #222222;\r\n");
      out.write("\t\tcolor:#f2f2f2;\r\n");
      out.write("\t\twidth:23%;\r\n");
      out.write("\t\theight:75%;\r\n");
      out.write("\t\tbox-sizing: border-box;\r\n");
      out.write("\t}\r\n");
      out.write(" \t\r\n");
      out.write(" \t\r\n");
      out.write(" \t\r\n");
      out.write(" \t/* Carousel 사진 슬라이드 */\r\n");
      out.write(" \t.container {\r\n");
      out.write(" \t\tpadding:0px;\r\n");
      out.write(" \t}\r\n");
      out.write("\t@media screen and (min-width: 768px) {\r\n");
      out.write("\t\t.container{\r\n");
      out.write("\t\t    width: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write(" \t/* 메인페이지의 연락처 DIV */\r\n");
      out.write(" \t#mainAddress {\r\n");
      out.write(" \t\twidth:100%;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write("\t/* 마이페이지 테이블 너비 */\r\n");
      out.write(" \ttable { \r\n");
      out.write(" \t\twidth: 90%; margin: 0 auto;\r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write(" \t/* 푸터 footer */\r\n");
      out.write(" \t/* Sticky footer styles\r\n");
      out.write("\t-------------------------------------------------- */\r\n");
      out.write("\thtml {\r\n");
      out.write("\t  position: relative;\r\n");
      out.write("\t  min-height: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\tbody {\r\n");
      out.write("\t  margin-bottom: 60px; /* Margin bottom by footer height */\r\n");
      out.write("\t}\r\n");
      out.write("\t.footer {\r\n");
      out.write("\t  position: absolute;\r\n");
      out.write("\t  bottom: 0;\r\n");
      out.write("\t  width: 100%;\r\n");
      out.write("\t  height: 60px; /* Set the fixed height of the footer here */\r\n");
      out.write("\t  line-height: 60px; /* Vertically center the text there */\r\n");
      out.write("\t  background-color: #f5f5f5;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/* Custom page CSS\r\n");
      out.write("\t-------------------------------------------------- */\r\n");
      out.write(" \t\r\n");
      out.write(" \t\r\n");
      out.write("\t/*스마트폰*/\r\n");
      out.write("\t@media screen and (min-width: 426px) and (max-width: 767px) {\r\n");
      out.write("\t\t/* body {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#contents_menu_top h3 {\r\n");
      out.write("\t\t\tfont-size: 16px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#contents_menu_bottom a {\r\n");
      out.write("\t\t\tfont-size: 10px;\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/*스마트폰 320~425 에서는 메뉴가 일렬로 나열됩니다. */\r\n");
      out.write("\t@media screen and (min-width: 320px) and (max-width: 425px) {\r\n");
      out.write("\t/* \tbody {\r\n");
      out.write("\t\t\twidth: 100%; */\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/******************태블릿PC******************/\r\n");
      out.write("\t@media screen and (min-width: 768px) and (max-width: 959px) {\r\n");
      out.write("\t/* \tbody {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t#contents_menu_top h3 {\r\n");
      out.write("\t\t\tfont-size: 24px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#contents_menu_bottom a {\r\n");
      out.write("\t\t\tfont-size: 14px;\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!-- 창원이형이 주신 css 끝 -->");
      out.write("\r\n");
      out.write("\r\n");

	//로그인 정보 세션
	String userEmail = CmmUtil.nvl( (String)session.getAttribute("userEmail") );
	String userNick = CmmUtil.nvl( (String)session.getAttribute("userNick") );
	String userSeq = CmmUtil.nvl((String)session.getAttribute("userSeq"));
	
	//위치정보 세션
	String myLat = CmmUtil.nvl((String)session.getAttribute("myLat"));	// 위도
	String myLon = CmmUtil.nvl((String)session.getAttribute("myLon"));	// 경도
	String myAddress = CmmUtil.nvl((String)session.getAttribute("myAddress")); // 내 주소 (지번)
	String regCode = CmmUtil.nvl((String)session.getAttribute("regCode"));	//지역코드 - 질병예방API용
	String skyCode = CmmUtil.nvl((String)session.getAttribute("skyCode"));  //skyCode 하늘상태(맑음:1, 구름조금:2, 구름많음:3, 흐림:4)
	String ptyCode = CmmUtil.nvl((String)session.getAttribute("ptyCode"));	//ptyCode 강수형태(없음:0, 비:1, 비/눈:2, 눈:3)
	String t3hCode = CmmUtil.nvl((String)session.getAttribute("t3hCode"));	//t3hCode 3시간 동안의 기온(단위 ℃)
	//nvl 널값이 들어오면 공백으로 바꿔줍니다.
	

      out.write("\r\n");
      out.write("\t<!-- 반응형 웹 설정 -->\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- 전체를 감싸는 DIV -->\r\n");
      out.write("    <div class=\"topContainer\">\r\n");
      out.write("    \t<!-- 1번째 행 메뉴 / 검색 / 컨테이너 -->\r\n");
      out.write("\t\t<div class=\"topSecondContainer\">\r\n");
      out.write("\t\t\t<!--------------------------메뉴부분 시작 -------------------------->\r\n");
      out.write("\t\t\t<div class=\"menuButton\">\r\n");
      out.write("\t\t\t\t<span style=\"font-size:30px;cursor:pointer\" onclick=\"openNav()\">\r\n");
      out.write("\t\t\t\t\t<img src=\"/resources/img/consumer/menu48x48.png\" height=\"42px\" style=\"margin-top:8px; margin-left:5px;\"/>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"mySidenav\" class=\"sidenav\">\r\n");
      out.write("\t\t\t\t<div id=\"sidenav_inner\">\r\n");
      out.write("\t\t\t\t\t<div><a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">닫기</a></div>\r\n");
      out.write("\t\t\t\t\t");
if(!"".equals(userEmail) && !"".equals(userSeq) && !"".equals(userNick)) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 로그인 된 상태 -->\r\n");
      out.write("\t\t\t\t\t\t<div><a href=\"Javascript:logout();\" >로그아웃</a></div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 로그인이 안된 상태 -->\r\n");
      out.write("\t\t\t\t\t\t<div><a href=\"/cmmn/main.do\">로그인</a></div>\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div><a href=\"/consumer/cnsmr/findMyLoc.do?userSeq=");
      out.print(userSeq);
      out.write("\">내 위치 설정</a></div>\t\t\r\n");
      out.write("\t\t\t\t\t<div><a href=\"/consumer/cnsmr/findAdjFt.do?locPosition=");
      out.print(myLat);
      out.write(',');
      out.print(myLon);
      out.write("&regCode=");
      out.print(regCode);
      out.write("\">근처 푸드트럭</a></div>\r\n");
      out.write("\t\t\t\t\t<div><a href=\"/consumer/weatherInfo.do?myAddress=");
      out.print(myAddress);
      out.write("&regCode=");
      out.print(regCode);
      out.write("\">날씨/질병 정보</a>\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div><a href=\"/consumer/user/mypage.do?userEmail=");
      out.print(userEmail);
      out.write("&userSeq=");
      out.print(userSeq );
      out.write("\">마이페이지</a></div>\r\n");
      out.write("\t\t\t\t\t<div><a href=\"/consumer/board/noticeList.do\">공지사항</a></div>\r\n");
      out.write("\t\t\t\t\t<div><a href=\"/consumer/board/boardList.do?userEmail=");
      out.print(userEmail);
      out.write("&userSeq=");
      out.print(userSeq );
      out.write("\" >고객센터</a></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"sidenav_outer\" onclick=\"closeNav()\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t<!--------------------------메뉴부분 종료 -------------------------->\r\n");
      out.write("\t\t\t<!-- 검색 버튼/창 DIV -->\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- 검색 돋보기 버튼 부분 -->\r\n");
      out.write("\t\t\t\t<div id=\"searchBttnContainer\">\r\n");
      out.write("\t\t\t\t\t<a id=\"searchButton\" href=\"javascript:void(0)\" onclick=\"toggleNav()\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/resources/img/consumer/magnifyingGlass48x48.png\" height=\"42px\" style=\"margin-top:8px; margin-right:5px;\"/>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- 로고 이미지 DIV -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"logo_main\">\r\n");
      out.write("\t\t\t\t<a href=\"/consumer/main.do\"><img src=\"/resources/img/consumer/logoWhite48x48.png\" height=\"46px\" style=\"margin-top:6px;\"/></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 1번째 행 종료 -->\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t<!-- 2번째 행 날씨정보 / 위치정보 -->\r\n");
      out.write(" \t\t<div style=\"clear:both\">\r\n");
      out.write("\t\t<div class=\"topFirstContainer\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"nav_top_left\" >\r\n");
      out.write("\t\t\t\t<!-- 날씨정보 / 값 받아 온 경우 -->\r\n");
      out.write("\t\t\t\t");
if(!"".equals(t3hCode)) {
      out.write("\r\n");
      out.write("\t\t\t\t\t");
if (ptyCode.equals("0")) {
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/resources/img/consumer/skyCode");
      out.print(skyCode);
      out.write(".png\" />\r\n");
      out.write("\t\t\t\t\t");
} else if(!(ptyCode.isEmpty())) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/resources/img/consumer/ptyCode");
      out.print(ptyCode);
      out.write(".png\" />\r\n");
      out.write("\t\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/consumer/weatherInfo.do?myAddress=");
      out.print(myAddress);
      out.write("&regCode=");
      out.print(regCode);
      out.write('"');
      out.write('>');
      out.print(t3hCode );
      out.write("℃</a>\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- 날씨정보/ 위치 설정 되지 않은 경우 -->\r\n");
      out.write("\t\t\t\t");
} else { 
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 위치 미 설정시 날씨 정보 공백 처리 -->\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"nav_top_right\" >\r\n");
      out.write("\t\t\t\t<!-- 위치정보 있을 경우-->\r\n");
      out.write("\t\t\t\t<img src=\"/resources/img/consumer/mapMarker.png\" style=\"height:12px; margin-bottom:2px; margin-right:3px\"/>\r\n");
      out.write("\t\t\t\t<a id=\"myLocLink\" href=\"/consumer/cnsmr/findMyLoc.do\"></a>\r\n");
      out.write("\t\t\t\t");
if(!"".equals(myAddress)) {
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/consumer/cnsmr/findMyLoc.do\">");
      out.print(myAddress);
      out.write("</a>\r\n");
      out.write("\t\t\t\t<!-- 좌표에서 주소변환을 위한 스크립트 끝 -->\r\n");
      out.write("\t\t\t\t<!-- 위치정보 없을 경우 -->\r\n");
      out.write("\t\t\t\t");
} else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"/consumer/cnsmr/findMyLoc.do\">위치를 설정해 주세요.</a>\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 2번째 행 종료 -->\r\n");
      out.write("\t\t<form method=\"POST\" action=\"/consumer/cnsmr/findFtByMenu.do\" style=\"margin:0;\">\r\n");
      out.write("\t\t\t<!-- 검색 박스 부분 (기본 숨겨진 상태/클릭시 열림) -->\r\n");
      out.write("\t\t\t<div id=\"searchBarContainer\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(myLat);
      out.write(',');
      out.print(myLon );
      out.write("\" name=\"locPosition\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(regCode);
      out.write("\" name=\"regCode\" />\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"keyWord\"  maxlength=\"15\" placeholder=\"메뉴를 검색하세요.\" style=\"margin-right:-5px;\"/>\r\n");
      out.write("\t\t\t\t<button type=\"submit\" id=\"submitBttn\">검색</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 푸터입니다. -->\r\n");
      out.write("\t<footer class=\"footer\">\r\n");
      out.write("\t\t<div class=\"container\" style=\"padding:0px 10px;\"><span class=\"text-muted\">© All Rights Reserved.</span></div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\r\n");
      out.write("<!-- 창원이형이 주신 top body끝  -->\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- 창원이형이 주신 top script  -->\r\n");
      out.write("<script>\r\n");
      out.write("\t\t/* 메뉴 열기 함수 */\r\n");
      out.write("\tfunction openNav() {\r\n");
      out.write("\t    document.getElementById(\"mySidenav\").style.width = \"200px\";\r\n");
      out.write("\t    document.getElementById('sidenav_outer').style.width=\"100%\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\t/* 메뉴 닫기 함수 */\r\n");
      out.write("\tfunction closeNav() {\r\n");
      out.write("\t    document.getElementById(\"mySidenav\").style.width = \"0\";\r\n");
      out.write("\t    document.getElementById('sidenav_outer').style.width=\"0\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 창원이형이 주신 top script  끝-->\r\n");
      out.write("\r\n");
      out.write("<!-- 검색 창 열기 기능 자바스크립트 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tvar check;\r\n");
      out.write("\twindow.onload=function(){\r\n");
      out.write("\t\tcheck=true;\r\n");
      out.write("\t};\r\n");
      out.write("\tfunction toggleNav() {\r\n");
      out.write("\t\tvar srchBarCon = document.getElementById(\"searchBarContainer\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(check){\r\n");
      out.write("\t\t    document.getElementById('searchButton').style.opacity = \"0.6\";\r\n");
      out.write("\t\t    srchBarCon.style.display = \"block\";\r\n");
      out.write("\t\t    check=false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t    document.getElementById('searchButton').style.opacity = \"1\";\r\n");
      out.write("\t\t    srchBarCon.style.display = \"none\";\r\n");
      out.write("\t\t    check=true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<!------------------------->\r\n");
      out.write("<!-- 로그아웃폼 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction logout() {\r\n");
      out.write("\t\tlocation.href=\"/cmmn/user/logout.do\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t/* 메인페이지 배너 양쪽 그림자 제거 */\r\n");
      out.write("\t.carousel-control.right, .carousel-control.left {\r\n");
      out.write("\t\tbackground-image:none;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 반응형을 위한 이미지 width 조정 */\r\n");
      out.write("\t.carousel-inner>.item>a>img, .carousel-inner>.item>img, .img-responsive, .thumbnail a>img {\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("</style>\r\n");
      out.write('\r');
      out.write('\n');
      out.write('	');
if(!imgDTOs.isEmpty()) {
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t  <div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t    <!-- Indicators -->\r\n");
      out.write("\t\t\t    <ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t      <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t      <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t      <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t      <li data-target=\"#myCarousel\" data-slide-to=\"3\"></li>\r\n");
      out.write("\t\t\t    </ol>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t    <!-- Wrapper for slides -->\r\n");
      out.write("\t\t\t\t");
if(imgDTOs != null && imgDTOs.isEmpty() == false) {
      out.write("\r\n");
      out.write("\t\t\t\t\t");
try { 
      out.write("\r\n");
      out.write("\t\t\t\t    <div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t      <div class=\"item active\">\r\n");
      out.write("\t\t\t\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/");
      out.print(imgDTOs.get(0).getFileSevname());
      out.write("\">\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t      <div class=\"item\">\r\n");
      out.write("\t\t\t\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/");
      out.print(imgDTOs.get(1).getFileSevname());
      out.write("\">\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t    \r\n");
      out.write("\t\t\t\t      <div class=\"item\">\r\n");
      out.write("\t\t\t\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/");
      out.print(imgDTOs.get(2).getFileSevname());
      out.write("\">\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t      <div class=\"item\">\r\n");
      out.write("\t\t\t\t        <img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/files/");
      out.print(imgDTOs.get(3).getFileSevname());
      out.write("\">\r\n");
      out.write("\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t");
} catch(IndexOutOfBoundsException ie){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t    <!-- Left and right controls -->\r\n");
      out.write("\t\t\t    <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t      <span class=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("\t\t\t      <span class=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t    </a>\r\n");
      out.write("\t\t\t    <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\r\n");
      out.write("\t\t\t      <span class=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("\t\t\t      <span class=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t    </a>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t<!-- 네번째 라인 (이벤트 배너) 끝 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"mainAddress\"  style=\"padding:50px;\">\r\n");
      out.write("\t\t\t<p>서울특별시 강서구 화곡동</p>\r\n");
      out.write("\t\t\t<p>Tel: 02-000-0000</p>\r\n");
      out.write("\t\t\t<p>Fax:02-000-0000</p>\r\n");
      out.write("\t\t\t<p>E-mail: foodtruck@Truck.com</p>\r\n");
      out.write("\t\t\t<br/>\r\n");
      out.write("\t\t\t<p>트럭왔냠의 사전 서면 동의 없이 트럭왔냠의 일체의 정보, 콘텐츠 및 UI등을\r\n");
      out.write("\t\t\t상업적 목적으로 전재, 전송, 스크래핑 등 무단 사용할 수 없습니다.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
