/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-08-20 04:32:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.admin.ft;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import poly.dto.admin.ADMIN_BoardDTO;
import java.util.List;
import poly.dto.admin.ADMIN_Ft_InfoDTO;
import java.util.List;

public final class ft_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/view/admin/ft/../admin_top.jsp", Long.valueOf(1534729901496L));
    _jspx_dependants.put("/WEB-INF/view/admin/ft/../admin_bottom.jsp", Long.valueOf(1534729902107L));
    _jspx_dependants.put("/WEB-INF/view/admin/ft/ft_table.jsp", Long.valueOf(1534729902145L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("poly.dto.admin.ADMIN_Ft_InfoDTO");
    _jspx_imports_classes.add("poly.dto.admin.ADMIN_BoardDTO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("<title>트럭왔냠 전체 관리자</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/admin/bootstrap.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js\"></script>\r\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("          \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/admin/bootstrap.css\">\r\n");
      out.write("\t\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tstyle=\"width: 350px; height: 25px; border-radius: 0 0 10px 10px; background-color: #454545; margin: 0 auto; color: #fefefe; padding-right: 10px; padding-left: 15px; padding-top: 2px;\">\r\n");
      out.write("\t\t\t<p align=\"center\" style=\"font-size: 12px;\">\r\n");
      out.write("\t\t\t\t<span style=\"color: #cccccc;\">관리자 접속일시 : 2018.06.04 18:29</span>\r\n");
      out.write("\t\t\t\t&nbsp;&nbsp;&nbsp;<input type=\"button\" value=\"로그아웃\"\r\n");
      out.write("\t\t\t\t\tonClick=\"location.href='#'\"\r\n");
      out.write("\t\t\t\t\tstyle=\"border: #333333 1px solid; background-color: #666666; width: 70px; height: 21px;\" />\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\tdata-toggle=\"collapse\" data-target=\"#myInverseNavbar2\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<strong> <a class=\"navbar-brand\" href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/admin_main.do\">트럭왔냠\r\n");
      out.write("\t\t\t\t\t관리자</a></strong>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"myInverseNavbar2\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">회원관리 <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/user/user_list.do\">회원정보관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">정지/탈퇴관리</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">푸드트럭관리\r\n");
      out.write("\t\t\t\t\t\t<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/ft/ft_list.do\">푸드트럭리스트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">정지/탈퇴관리</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/board/board_list.do\">게시판관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/admin/board_p/board_p_list.do\">게시물관리</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">쿠폰관리\r\n");
      out.write("\t\t\t\t\t\t<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/coupon/coupon_main.do?cmd=coupon_list\">쿠폰만들기/리스트</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/admin/coupon/coupon_main.do?cmd=coupon_issue_list\">쿠폰발급/조회</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">결제관리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">배너/팝업관리</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /.navbar-collapse -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /.container-fluid -->\r\n");
      out.write("</nav>\r\n");
      out.write("\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/admin/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/admin/jquery-1.11.2.min.js\"></script>\r\n");
      out.write("\t<!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<h2>푸드트럭리스트</h2>\r\n");
      out.write("    <div style=\"border-bottom:1px solid #444444; margin-top:15px;\"></div>\r\n");
      out.write("\t<div style=\"margin-top:15px; margin-bottom:25px;\">\r\n");
      out.write("        <form class=\"form-inline\" action=\"");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_search_list.do\" method=\"GET\">\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("            \t<h4>푸드트럭 검색</h4>\r\n");
      out.write("                    <select class=\"form-control\" name=\"option\">\r\n");
      out.write("                        <option value=\"ft_name\">푸드트럭 이름</option>\r\n");
      out.write("                        <option value=\"sel_no\">사업자 번호</option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <input type=\"text\" name=\"value\" class=\"form-control\">\r\n");
      out.write("                    <input type=\"submit\" value=\"검색\" class=\"btn btn-default\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"border-bottom:1px solid #cccccc; margin-top:15px; margin-bottom:15px;\"></div>\r\n");
      out.write("\t<div id=\"table_container\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write(" ");
 
 	List<ADMIN_Ft_InfoDTO> ftDTOArr = (List<ADMIN_Ft_InfoDTO>)request.getAttribute("ftList");
 	
 	if(ftDTOArr == null){
 		ftDTOArr = (List<ADMIN_Ft_InfoDTO>)request.getAttribute("ft_SearchList");
 	}
 	
	 String pageNum = (String)request.getAttribute("pageNum");
		int startNum;
		if (pageNum==null || pageNum.equals("null")){//새로 목록을 불러올때 무조건 1페이지를 표시하게끔
			pageNum = "1";
			startNum = 1;
		}else{
			startNum = Integer.parseInt(pageNum); //현재 표시되는 페이지번호
		}
		
		String TopageSize=(String)request.getAttribute("pageSize");
		int pageSize;
		if(TopageSize==null || TopageSize.equals("null")){
			pageSize=10;
		}else{
			pageSize=Integer.parseInt(TopageSize);
		}
 
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html\" >\r\n");
      out.write("\t\t<title>푸드트럭리스트</title>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- include javascript and css files for the EditableGrid library -->\r\n");
      out.write("\t\t<!--<script src=\"../editablegrid-1.0.10.js\"></script>-->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/admin/editablegrid-1.0.10.css\"  type=\"text/css\" />\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- include javascript and css files for this demo -->\r\n");
      out.write("\t\t<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/js/admin/demo.js\" ></script>\r\n");
      out.write("\t\t<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/admin/demo.css\" /> \r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/css/admin/bootstrap.css\">\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction pageSizeEdit(pageSize){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_list.do?pageSize=\"+pageSize+\"&pageNum=");
      out.print(pageNum);
      out.write("\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tfunction allCheck(){\r\n");
      out.write("\t\t\t\t  cbox = input_form.ft_check;\r\n");
      out.write("\t\t\t\t    if(cbox.length) {  // 여러 개일 경우\r\n");
      out.write("\t\t\t\t        for(var i = 0; i<cbox.length;i++) {\r\n");
      out.write("\t\t\t\t            cbox[i].checked=input_form.all.checked;\r\n");
      out.write("\t\t\t\t        }\r\n");
      out.write("\t\t\t\t    } else { // 한 개일 경우\r\n");
      out.write("\t\t\t\t        cbox.checked=input_form.all.checked;\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tfunction checkFT(mode){\r\n");
      out.write("\t\t\t\tvar cObj = document.getElementsByName(\"ft_check\"); //체크박스 값 받는 곳\r\n");
      out.write("\t\t\t\tvar check_Cnt = 0;\r\n");
      out.write("\t\t\t\tvar check_Arr = \"\"; //선택항목 값 담는 곳\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tfor(var i=0; i<cObj.length; i++){\r\n");
      out.write("\t\t\t\t\tif(cObj[i].checked){\r\n");
      out.write("\t\t\t\t\t\tcheck_Arr += cObj[i].value+',';\r\n");
      out.write("\t\t\t\t\t\tcheck_Cnt++;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(mode==1 && check_Cnt != 0){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_active.do?ArrFt_Seq=\"+check_Arr;\r\n");
      out.write("\t\t\t\t}else if(mode==2 && check_Cnt != 0){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_drop.do?ArrFt_Seq=\"+check_Arr;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<div style=\"position:relative; float:left; width:68%;\">\r\n");
      out.write("            \t\t<p>전체 푸드트럭 수 : ");
      out.print(ftDTOArr.size() );
      out.write("</p>\r\n");
      out.write("                   선택 푸드트럭&nbsp; \r\n");
      out.write("                   <input type=\"button\" value=\"활동정지\" class=\"btn btn-default\" onClick=\"javascript:checkFT(1)\"> \r\n");
      out.write("                   <input type=\"button\" value=\"강제탈퇴\" class=\"btn btn-default\" onClick=\"javascript:checkFT(2)\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"float:right; width:32%; padding-top:30px;\">\r\n");
      out.write("                    <div style=\" position:relative; float:right;\">\r\n");
      out.write("                           <select name=\"boardCount\" class=\"form-control\" onchange=\"pageSizeEdit(this.value)\">\r\n");
      out.write("\t\t\t\t\t\t\t<option selected=\"selected\">");
      out.print(pageSize);
      out.write("개씩 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"10\">10개씩 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"15\">15개씩 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"30\">30개씩 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"50\">50개씩 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"100\">100개씩 보기</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        <div style=\"clear:both;\"></div>\r\n");
      out.write("\t\t<!-- In real life this HTML table would have been generated with eg. a PHP server-side script -->\r\n");
      out.write("\t\t<!--  The first row of your table will serve as table header, you don't have to put it in a <THEAD> but it's better of course -->\r\n");
      out.write("        <form name=\"input_form\">\r\n");
      out.write("        <table id=\"htmlgrid\" class=\"testgrid\" style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("            \t<th width=\"2%\"><input type=\"checkbox\" name=\"all\" onClick=\"allCheck()\"/></th>\r\n");
      out.write("\t\t\t\t<th width=\"10%\">푸드트럭번호</th>\r\n");
      out.write("\t\t\t\t<th width=\"30%\">푸드트럭 이름</th>\r\n");
      out.write("\t\t\t\t<th width=\"20%\">이메일</th>\r\n");
      out.write("\t\t\t\t<th>사업자 번호</th>\r\n");
      out.write("\t\t\t\t<th>푸드트럭 가입일</th>\r\n");
      out.write("\t\t\t\t<th>활동상태</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t");

				if(ftDTOArr.size()==0 || ftDTOArr==null){
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr height=\"80px\"><td align=\"center\" colspan=\"7\">가입된 푸드트럭이 없습니다.</td></tr>\t\r\n");
      out.write("\t\t\t\t");
}else{
				int startCnt=(startNum-1)*pageSize;	//시작 그룹번호
				int endCnt=pageSize*startNum; //끝 그룹번호
				int cnt = 0;
				for(int i=startCnt; i<endCnt; i++){
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr id=\"");
      out.print(cnt);
      out.write("\"> \r\n");
      out.write("\t            \t<td><input type=\"checkbox\" name=\"ft_check\" value=\"");
      out.print(ftDTOArr.get(i).getFt_seq());
      out.write("\"/></td>\r\n");
      out.write("\t                <td>");
      out.print(ftDTOArr.get(i).getFt_seq());
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td  style=\"cursor:pointer;\" onclick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_info.do?ft_seq=");
      out.print(ftDTOArr.get(i).getFt_seq());
      out.write("'\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.print(ftDTOArr.get(i).getFt_name() );
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>유저 이메일 (닉네임)</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(ftDTOArr.get(i).getSel_no() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>");
      out.print(ftDTOArr.get(i).getFt_join() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t");
if(ftDTOArr.get(i).getFt_status()==0){ 
      out.write('정');
      out.write('상');
}
						else if(ftDTOArr.get(i).getFt_status()==1){ 
      out.write("활동정지");
}
						else if(ftDTOArr.get(i).getFt_status()==-1){ 
      out.write("탈퇴대기");
}
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
cnt++;
					
					if(ftDTOArr.size()==i+1)break;
				} 
			}
			
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<div style=\"margin-top:10px;\">\r\n");
      out.write("\t\t\t<div class=\"form-group\"  style=\"position:relative; float:left;\">\r\n");
      out.write("\t         선택 푸드트럭&nbsp; \r\n");
      out.write("         \t\t<input type=\"button\" value=\"활동정지\" class=\"btn btn-default\" onClick=\"javascript:checkFT(1)\"> \r\n");
      out.write("                <input type=\"button\" value=\"강제탈퇴\" class=\"btn btn-default\" onClick=\"javascript:checkFT(2)\">\r\n");
      out.write("\t    \t</div>\r\n");
      out.write("\t     </div>\r\n");
      out.write("\t\t<div  id=\"edition\"  align=\"center\"  style=\"clear:both;\">\r\n");
      out.write("        \t");
if (ftDTOArr.size()>0){
				int pageCount = ftDTOArr.size()/pageSize + (ftDTOArr.size()%pageSize==0 ? 0 : 1); // 게시글 전체개수/한 페이지에 표시되는 게시글수
				int pageBlock = 5;
				int startPage = ((startNum-1)/pageBlock) * pageBlock + 1;
				int endPage = startPage + pageBlock - 1;
				if (endPage>pageCount) endPage = pageCount;
				
				if (startPage>pageBlock){
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"<\" class=\"btn btn-default\" onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_list.do?pageNum=");
      out.print(startPage-pageBlock);
      out.write("&pageSize=");
      out.print(pageSize);
      out.write("''\">\r\n");
      out.write("\t");
		}
				for(int i=startPage; i<=endPage; ++i){
      out.write("\r\n");
      out.write("\t\t\t\t");
if(Integer.parseInt(pageNum)==i){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"");
      out.print(i );
      out.write("\" class=\"btn btn-primary\"  onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_list.do?pageNum=");
      out.print(i);
      out.write("&pageSize=");
      out.print(pageSize);
      out.write("'\">\t\t\r\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"");
      out.print(i );
      out.write("\" class=\"btn btn-default\"  onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_list.do?pageNum=");
      out.print(i);
      out.write("&pageSize=");
      out.print(pageSize);
      out.write("'\">\t\t\r\n");
      out.write("\t\t\t\t");
} 
      out.write('\r');
      out.write('\n');
      out.write('	');
		}
				if (endPage<pageCount){
      out.write("\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\">\" class=\"btn btn-default\" onClick=\"location.href='");
      out.print(request.getContextPath());
      out.write("/admin/ft/ft_list.do?pageNum=");
      out.print(startPage+pageBlock);
      out.write("&pageSize=");
      out.print(pageSize);
      out.write("'\">\r\n");
      out.write("\t");
		}
			}

      out.write("\r\n");
      out.write("        </div>\t\t\t\r\n");
      out.write("\t</body>\r\n");
      out.write("\t\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("    \t<!-- <iframe src=\"./editablegrid-1.0.10/examples/ft_table.html\" width=\"100%\" style=\"border:0px; max-height:auto; min-height:450px;\"></iframe> -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"border-bottom:1px solid #cccccc; margin-top:15px;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<hr>\r\n");
      out.write("<footer class=\"text-center\">\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-xs-12\">\r\n");
      out.write("\t\t\t<p>Copyright © 트럭왔냠. All rights reserved.</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- jQuery (necessary for Bootstrap's JavaScript plugins) --> \r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/admin/jquery-1.11.2.min.js\"></script> \r\n");
      out.write("<!-- Include all compiled plugins (below), or include individual files as needed --> \r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/resources/js/admin/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
